setwd("E:\\R training Chennai\\Big D  ")
getwd()
#########reading the data########
test <- read.csv("test1.csv", header = TRUE,sep = ',' ,na.strings=c("NA","NAN"," ") )
train<- read.csv("train1.csv", header = TRUE, sep = ",", na.string=c("NA","NAN", " "))
#####Audit the data#####
str(train)
summary(train)
##########imputation of missing values################
train$Item_Weight <- ifelse(is.na(train$Item_Weight), median(train$Item_Weight, na.rm = TRUE), train$Item_Weight)
sum(is.na(train$Item_Weight))
####Solving inconsistancy in Item Fat Content########
train$Item_Fat_Content<- as.character(train$Item_Fat_Content)
is.character(train$Item_Fat_Content)
train$Item_Fat_Content<-ifelse(train$Item_Fat_Content=="LF", "Low Fat", train$Item_Fat_Content)
train$Item_Fat_Content<- ifelse(train$Item_Fat_Content=="low fat", "Low Fat", train$Item_Fat_Content)
train$Item_Fat_Content<- ifelse(train$Item_Fat_Content== "reg", "Regular", train$Item_Fat_Content)
train$Item_Fat_Content<- as.factor(train$Item_Fat_Content)
str(train)
summary(train)
train$Outlet_Size<-as.character(train$Outlet_Size)
train$Outlet_Size<-ifelse(train$Outlet_Size == '', "Medium" , train$Outlet_Size)
train$Outlet_Size<-as.factor(train$Outlet_Size)
str(train)
summary(train)
library(e1071)
skewness(train$Item_Weight)
boxplot(train$Item_Weight)
skewness(train$Item_Visibility)
boxplot(train$Item_Visibility)
skewness(train$Item_MRP)
boxplot(train$Item_MRP)
skewness(train$Outlet_Sales)
boxplot(train$Outlet_Sales)
tbl=table(train$Outlet_Location_Type, train$Outlet_Size)
tbl
library(MASS)
chisq.test(tbl)
tbl1 <- table(train$Item_Fat_Content, train$Item_Type)
tbl1
chisq.test(tbl1)
tbl2<-table(train$Outlet_Type, train$Outlet_Location_Type)
tbl2
chisq.test(tbl2)
cor(train$Item_Weight, train$Item_Visibility)
cor(train$Item_Weight, train$Item_MRP)
cor(train$Item_Visibility, train$Item_MRP)
cor(train$Item_MRP, train$Outlet_Sales)
cor(train$Item_Weight, train$Outlet_Sales)
cor(train$Item_Visibility, train$Outlet_Sales)
library(Hmisc)
describe(train)
plot(train$Item_MRP, train$Outlet_Sales)
plot(train$Item_Weight, train$Item_MRP)
plot(train$Item_Visibility, train$Item_MRP)
train$Ln_Item_Weight<-log(train$Item_Weight)
skewness(train$Ln_Item_Weight) ###Skewnwss has increased so we have applied another technique of scalling
skewness(train$Item_Weight)
train$Item_Weight_Scale <-scale(train$Item_Weight)
skewness(train$Item_Weight_Scale)
names(train)
########creating new variable
train$YOB <- 2019-train$Outlet_Establishment_Year
#######applying a regression model
model<- lm(Outlet_Sales~Item_Weight+Item_Visibility+Item_MRP+YOB, data=train)
summary(model)
train$preds_sales <- predict(model,train)
rmse_model<-sqrt(mean((train$Outlet_Sales-train$preds_sales)^2))
print(rmse_model)
names(train)
#####################error area################
model1<-lm(Outlet_Sales~Item_Weight+Item_Fat_Content+Item_Visibility
           +Item_Type+Item_MRP+Outlet_Size+Outlet_Location_Type+Outlet_Type+YOB)
summary(model1)
train$preds_sales_model1 <- predict(model1, train)
rmse_model1<- sqrt(mean((train$Outlet_Sales-train$preds_sales_model1)^2))
print(rmse_model1)


test$Item_Weight<-ifelse(is.na(test$Item_Weight), median(test$Item_Weight,na.rm=TRUE), test$Item_Weight)
sum(is.na(test$Item_Weight))
test$Item_Fat_Content<- as.character(test$Item_Fat_Content)
test$Item_Fat_Content<- ifelse(test$Item_Fat_Content == 'LF', 'Low Fat', test$Item_Fat_Content)
test$Item_Fat_Content<- ifelse(test$Item_Fat_Content == 'low fat', 'Low Fat', test$Item_Fat_Content)
test$Item_Fat_Content<- ifelse(test$Item_Fat_Content == 'reg', 'Regular', test$Item_Fat_Content)
table(test$Item_Fat_Content)
test$Item_Fat_Content <-as.factor(test$Item_Fat_Content)
str(test)
summary(test)
test$Outlet_Size<- as.character(test$Outlet_Size)
test$Outlet_Size<- ifelse(test$Outlet_Size=='', 'Medium', test$Outlet_Size)
test$Outlet_Size<- as.factor(test$Outlet_Size)
test$YOB <- 2019-test$Outlet_Establishment_Year
summary(test)
test$sale_preds_reg <- predict(model1, test)
#####writing back to CSV file###########
submission<- c('Item_identifier', 'Outlet_Identifier', 'Sales_preds_reg')
submit<- test[sbmission]
write.csv(submit, "submission.csv", row.names = TRUE)
